name: Tag production image for neur1630
on: [workflow_dispatch]

env:
  CLASS: neur1630
  TARGET: r_lang
  SQLITE: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID_JH_DOCKER }}
          service_account_key: ${{ secrets.GCP_SA_KEY_JH_DOCKER }}
          export_default_credentials: true

      - name: Create Julia Environment Files
        if: env.TARGET == 'r_julia'
        run: |
          sudo --preserve-env=CLASS docker-compose up julia_build

      - name: Upload Julia Env Files to Google Storage Bucket
        if: env.TARGET == 'r_julia'
        run: |
          gsutil cp -r requirements/classes/neur1630/julia_env gs://jupyterhub-environment-files/fall-2020/neur1630/past/${GITHUB_SHA}/julia
          gsutil cp -r requirements/classes/neur1630/julia_env gs://jupyterhub-environment-files/fall-2020/neur1630/latest/julia

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push JH Image
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up jh_image
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/neur1630:${GITHUB_REF##*/}
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/neur1630:${GITHUB_SHA}
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/neur1630:latest
          docker tag jupyterhub-docker-images_jh_image:latest gcr.io/jupyterhub-docker-images/neur1630:fall-2020
          docker push gcr.io/jupyterhub-docker-images/neur1630:latest
          docker push gcr.io/jupyterhub-docker-images/neur1630:fall-2020
          docker push gcr.io/jupyterhub-docker-images/neur1630:${GITHUB_REF##*/}
          docker push gcr.io/jupyterhub-docker-images/neur1630:${GITHUB_SHA}

      - name: Upload Conda Env Files to Google Storage Bucket
        run: |
          gsutil cp -r requirements/out gs://jupyterhub-environment-files/fall-2020/neur1630/past/${GITHUB_SHA}/conda
          gsutil cp -r requirements/out gs://jupyterhub-environment-files/fall-2020/neur1630/latest/conda