name: build-image-php1560
on: 
  push:
      paths:
      - 'requirements/classes/php1560/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'scripts/**'
      - '.github/workflows/php1560.yml'
  workflow_dispatch:

env:
  CLASS: php1560
  TARGET: r_lang
  SQLITE: false
  PYTHON_VERSION: "3.9.17"
  PROJECT_ID: jupyterhub-docker-images
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/jupyterhub-docker-images/all-classes/php1560

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Setup Google Service Account
        run:  echo '${{ secrets.SA_KEY_JH_DOCKER_2025}}' | base64 -d > ./creds.json

      - name: Auth GCloud
        uses: google-github-actions/auth@v2.1.12
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_JH_DOCKER }}
          credentials_json: "./creds.json"

      - name: Set Up GCloud
        uses: google-github-actions/setup-gcloud@v2.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_JH_DOCKER }}

      - name: Create Julia Environment Files
        if: env.TARGET == 'r_julia'
        run: |
          sudo --preserve-env=CLASS docker compose up julia_build

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build JH Image
        run: |
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose up jh_image

      - name: Tag JH Image
        run: |
          docker tag ${{ env.CLASS }}:latest ${{ env.GAR_LOCATION }}:${GITHUB_REF##*/}
          docker tag ${{ env.CLASS }}:latest ${{ env.GAR_LOCATION }}:latest

      - name: Push JH Image
        run: |
          docker push ${{ env.GAR_LOCATION }}:latest
          docker push ${{ env.GAR_LOCATION }}:${GITHUB_REF##*/}